// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Link struct {
	ID      int64         `json:"id"`
	Title   string        `json:"title"`
	Address string        `json:"address"`
	UserID  sql.NullInt64 `json:"user_id"`
}

type User struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}
